-- 1

DROP TABLE V_ACCIDENTES;
DROP TABLE V_VEHICULOS;
DROP TABLE V_CLIENTES;

CREATE TABLE V_CLIENTES (
    DNI VARCHAR(9) CONSTRAINT PK_CLIENTES PRIMARY KEY,
    NOMBRE VARCHAR2(20) UNIQUE NOT NULL,
    APELLIDOS VARCHAR2(30),
    SEXO CHAR,
    DIRECCION VARCHAR2(100),
    TELEFONO NUMBER(9,0)
);

CREATE TABLE V_VEHICULOS (
    MATRICULA VARCHAR2(8) CONSTRAINT PK_VEHICULOS PRIMARY KEY,
    MARCA VARCHAR2(15),
    MODELO VARCHAR2(25),
    POTENCIA NUMBER(5,0) 
        CONSTRAINT CK_POTENCIA 
        CHECK(POTENCIA >= 500 AND POTENCIA <= 10000),
    TIPO_SEGURO VARCHAR2(10),
    PRECIO NUMBER(8,2),
    DNI_CLIENTE VARCHAR(9),
    CONSTRAINT FK_V_CLIENTES_DNI_CLIENTE 
    FOREIGN KEY(DNI_CLIENTE) 
    REFERENCES V_CLIENTES(DNI)
);

CREATE TABLE V_VEHIC_ACCID (
    MATRICULA VARCHAR2(8) CONSTRAINT PK_VEHICULOS_ACCID PRIMARY KEY,
    FECHA DATE 
        CONSTRAINT CK_FECHA 
        CHECK(FECHA BETWEEN TO_DATE('01-01-1950', 'dd-mm-yyyy') AND 
                TO_DATE('31-12-2050', 'dd-mm-yyyy')),
    RESPONSABLE CHAR 
        CONSTRAINT CK_RESPONSABLE
        CHECK(RESPONSABLE IN('S', 'N')),
    DESCRIPCION VARCHAR2(100),
    CONSTRAINT FK_V_VEHIC_ACCID_MATRICULA
    FOREIGN KEY(MATRICULA) 
    REFERENCES V_VEHICULOS(MATRICULA)
);

-- 2

-- 2.1
ALTER TABLE V_CLIENTES ADD FECHA_NAC DATE;

-- 2.2
ALTER TABLE V_CLIENTES ADD POBLACION VARCHAR2(50) DEFAULT 'CIUDAD REAL';

-- 2.3
ALTER TABLE V_CLIENTES ADD CONSTRAINT CK_FECHA_NAC 
     CHECK(FECHA_NAC BETWEEN TO_DATE('01-01-1920', 'dd-mm-yyyy') AND 
                TO_DATE('01-01-2100', 'dd-mm-yyyy'));

-- 2.4
ALTER TABLE V_CLIENTES DROP COLUMN APELLIDOS;

ALTER TABLE V_CLIENTES ADD APELLIDO_PRIMERO VARCHAR2(20);
ALTER TABLE V_CLIENTES ADD APELLIDO_SEGUNDO VARCHAR2(20);

-- 2.5
ALTER TABLE V_VEHICULOS DROP CONSTRAINT CK_POTENCIA;

-- 2.6
ALTER TABLE V_CLIENTES ADD CONSTRAINT CK_SEXO
    CHECK(SEXO IN ('S', 'N'));

-- 2.7
ALTER TABLE V_CLIENTES ADD ID_CLIENTE NUMBER(8,0);

-- 2.8
ALTER TABLE V_VEHICULOS DROP CONSTRAINT FK_V_CLIENTES_DNI_CLIENTE;
ALTER TABLE V_VEHICULOS DROP COLUMN DNI_CLIENTE;

ALTER TABLE V_CLIENTES DROP CONSTRAINT PK_CLIENTES;
ALTER TABLE V_CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY(ID_CLIENTE);

ALTER TABLE V_VEHICULOS ADD ID_CLIENTE NUMBER(8,0);
ALTER TABLE V_VEHICULOS ADD CONSTRAINT FK_V_VEHICULOS_ID_CLIENTE 
    FOREIGN KEY(ID_CLIENTE) 
    REFERENCES V_CLIENTES(ID_CLIENTE);


-- 2.9
RENAME V_VEHIC_ACCID TO V_ACCIDENTES;

-- 2.10
DROP TABLE V_VEHICULOS;

-- 3

DROP USER USUPRAC;

-- 3.1

alter session set "_ORACLE_SCRIPT"=true;
create user USUPRAC identified by BD02 
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;

-- 3.2
GRANT CONNECT, RESOURCE TO USUPRAC;

-- 3.3
GRANT INSERT, UPDATE ON V_CLIENTES TO USUPRAC WITH GRANT OPTION;

-- 3.4
REVOKE UPDATE ON V_CLIENTES FROM USUPRAC;
