
-- APARTADO 1

drop table AVISOS;
drop table TECNICOS;
drop table TIENDAS;
drop table CADENAS;

CREATE TABLE CADENAS (
    CODIGO CHAR PRIMARY KEY,
    DESCRIPCION VARCHAR2(100),
    CONSTRAINT check_codigo CHECK (CODIGO in ('D', 'A', 'C', 'L', 'M')),
    CONSTRAINT check_descripcion CHECK (DESCRIPCION = upper(DESCRIPCION))
);

CREATE TABLE TIENDAS (
    CADENA CHAR,
    ORDEN VARCHAR2(5),
    DIRECCION VARCHAR2(40),
    LOCALIDAD VARCHAR2(40),
    FECHA_APERTURA DATE DEFAULT SYSDATE,
    GARANTIA CHAR,
    CONSTRAINT pk_tiendas PRIMARY KEY (CADENA, ORDEN),
    CONSTRAINT check_garantia CHECK(GARANTIA in ('S', 'N')),
    CONSTRAINT fk_cadenas FOREIGN KEY (CADENA) REFERENCES CADENAS(CODIGO),
    CONSTRAINT check_orden CHECK(REGEXP_LIKE(ORDEN, '^[0-9]{5}$'))
);

CREATE TABLE TECNICOS (
    DNI VARCHAR2(9) PRIMARY KEY,
    NOMBRE VARCHAR2(20) NOT NULL,
    APELLIDO1 VARCHAR2(20) NOT NULL,
    APELLIDO2 VARCHAR2(20) NULL,
    TELEFONO NUMBER(8,0) NULL,
    FECHA_NACIMIENTO DATE NULL,
    COSTE_HORA NUMBER(8,2) NOT NULL,
    CONSTRAINT check_dni CHECK(REGEXP_LIKE(DNI, '^[0-9]{8}[A-Z]$'))
);

CREATE TABLE AVISOS (
    NUM NUMBER(6,0) PRIMARY KEY,
    FECHA DATE,
    CADENA_TIENDA CHAR NOT NULL,
    ORDEN_TIENDA VARCHAR2(5) NOT NULL,
    DNI_TECNICO VARCHAR2(9) NOT NULL,
    CONSTRAINT fk_tienda FOREIGN KEY (CADENA_TIENDA, ORDEN_TIENDA) REFERENCES TIENDAS(CADENA, ORDEN),
    CONSTRAINT fk_tecnico FOREIGN KEY (DNI_TECNICO) REFERENCES TECNICOS(DNI)
);

-- Comprobamos la tabla cadenas
INSERT INTO CADENAS VALUES ('D', 'CADENA D'); -- Correcto
INSERT INTO CADENAS VALUES ('K', 'CADENA K'); -- Incorrecto
INSERT INTO CADENAS VALUES ('A', 'cadena a'); -- Incorrecto

-- Comprobamos la tabla tiendas
INSERT INTO TIENDAS (CADENA, ORDEN, DIRECCION, LOCALIDAD, GARANTIA) VALUES('A', '12345', 'Dir 1', 'Loc 1', 'S'); -- Incorrecto
INSERT INTO TIENDAS (CADENA, ORDEN, DIRECCION, LOCALIDAD, GARANTIA) VALUES('D', '12345', 'Dir 1', 'Loc 1', 'S'); -- Correcto
INSERT INTO TIENDAS (CADENA, ORDEN, DIRECCION, LOCALIDAD, GARANTIA) VALUES('D', '54321', 'Dir 1', 'Loc 1', 'K'); -- Incorrecto
INSERT INTO TIENDAS (CADENA, ORDEN, DIRECCION, LOCALIDAD, GARANTIA) VALUES('D', 'HOLA', 'Dir 1', 'Loc 1', 'S'); -- Incorrecto

-- Comprobamos la tabla tecnicos
    
INSERT INTO TECNICOS (DNI, NOMBRE, APELLIDO1, COSTE_HORA) VALUES('12345678A', 'nombre', 'ape1', 10.50); -- Correcto
INSERT INTO TECNICOS (DNI, NOMBRE, APELLIDO1, COSTE_HORA) VALUES('12345BBBA', 'nombre', 'ape1', 10.50); -- Incorrecto

-- Comprobamos la tabla avisos

INSERT INTO AVISOS VALUES(111111, SYSDATE, 'D', '12345', '12345678A'); -- Correcto
INSERT INTO AVISOS VALUES(111111, SYSDATE, 'D', '1234', '1234567A'); -- Incorrecto
INSERT INTO AVISOS VALUES(111111, SYSDATE, 'D', '12345', '1234567A'); -- Incorrecto

-- Borrado de datos
delete from AVISOS;
delete from TECNICOS;
delete from TIENDAS;
delete from CADENAS;

--- APARTADO 2


-- A

ALTER TABLE AVISOS ADD tiempo_empleado NUMBER(3,0) DEFAULT 30 CHECK(tiempo_empleado >= 10 and tiempo_empleado<=180);

-- B

create index IND_AVISOS on AVISOS(FECHA, COD_TIENDA);

-- C

ALTER TABLE CADENAS DROP CONSTRAINT check_descripcion;

-- D

ALTER TABLE AVISOS DROP PRIMARY KEY;
ALTER TABLE AVISOS ADD CONSTRAINT fk_avisos PRIMARY KEY(FECHA, DNI_TECNICO);

-- E

create user AGARCIA identified by VER34;
 
grant all privileges on CADENAS to AGARCIA;
grant all privileges on TECNICOS to AGARCIA;
grant all privileges on TIENDAS to AGARCIA;
grant SELECT on AVISOS to AGARCIA;
